# Generated by Django 5.0.1 on 2024-10-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_borrowhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowhistory',
            options={'ordering': ['-borrow_date'], 'permissions': (('can_view_borrow_history', 'Can view borrow history'),)},
        ),
    ]
