# Generated by Django 5.0.1 on 2024-10-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_borrowhistory_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowHistory',
        ),
    ]
