# Generated by Django 5.0.1 on 2024-10-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_book_quantity_borrowhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowhistory',
            options={'verbose_name': 'Borrow History', 'verbose_name_plural': 'Borrow Histories'},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'On loan'), ('a', 'Available')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
